server:
  port: 8080
spring:
  application:
    name: lms_backend
  datasource:
    url: jdbc:postgresql://dpg-d490qt0gjchc73f58km0-a/lms_db_u041
    username: lms_db_u041_user
    password: LKKBbIiVtqudxTa62PQ9B8FqRR0DJXNP
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 10000
      connection-timeout: 20000
      pool-name: HikariPool-LMS
  #    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
#    url: jdbc:sqlserver://host.docker.internal:1433;databaseName=lms_dbv1;encrypt=true;trustServerCertificate=true
#    username: sa
#    password: MyS3cureP@ss!
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect #org.hibernate.dialect.SQLServer2012Dialect
#        cache:
#          use_second_level_cache: true
#          use_query_cache: true
#          region.factory_class: org.hibernate.cache.jcache.JCacheRegionFactory
    open-in-view: false
default:
  role: ROLE_USER  # SpEL
jwt:
  secret: thisIsAStrongMySecretKeySpringSecurity2025


springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha


